use_frameworks!

platform :ios, '8.0'

target 'CompontentTests_Example' do
  pod 'CompontentTests', :path => '../'

  target 'CompontentTests_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
